# Generated by Django 5.1.6 on 2025-03-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Eco", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationallink",
            name="description",
            field=models.TextField(),
        ),
    ]
