# Generated by Django 5.1.5 on 2025-03-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eco', '0002_userprofile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
