# Generated by Django 5.1.5 on 2025-03-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eco', '0003_challenge_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='rank',
        ),
    ]
