# Generated by Django 5.1.5 on 2025-03-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eco', '0004_remove_leaderboard_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AlterField(
            model_name='user_challenge_log_entry',
            name='date_logged',
            field=models.DateTimeField(),
        ),
    ]
