# Generated by Django 5.1.5 on 2025-03-13 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eco', '0005_remove_userprofile_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='point_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
