# Generated by Django 5.1.5 on 2025-03-13 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eco', '0006_alter_challenge_point_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitted_challenge',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='submitted_challenge',
            name='user',
        ),
        migrations.AddField(
            model_name='submitted_challenge',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submitted_challenge',
            name='description',
            field=models.TextField(default='No description provided.', max_length=750),
        ),
        migrations.AddField(
            model_name='submitted_challenge',
            name='point_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submitted_challenge',
            name='title',
            field=models.CharField(default='No title provided.', max_length=128),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(max_length=750),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='point_value',
            field=models.IntegerField(verbose_name=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
